name: crypto-workflow
on: workflow_dispatch
jobs:
  crypto-harvester:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install python version needed

      - name: install python packages needed
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python crypto.py
          
      - name: commit files
        run: |
          git config --local user.email "chrismbev83@gmail.com"
          git config --local user.name "ChrisMbeva"
          git add -A
          gitt diff-index --quiet HEAD || (git commit -a -m "updated data" --allow-empty)
          
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
        
